apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: a69tjc2xr-python 
  janus-idp.io/tekton: a69tjc2xr-python
  backstage.io/kubernetes-id: a69tjc2xr-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: a69tjc2xr-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml